export const properties = [
    {
      id: 1,
      title: "Super Soray",
      price: "$750,000",
      address: "1012 Oak Avenue, Manchester, Comrat City",
      beds: 3,
      baths: 2,
      area: "900 sqft",
      image: "/images/properties/saray-lyxury/30329833.jpg",
      type: "FOR SALE",
    },
    {
      id: 2,
      title: "Oakview Residence",
      price: "$600,000",
      address: "4567 Lavender Way, Sydney, Australia",
      beds: 3,
      baths: 2,
      area: "900 sqft",
      image: "/images/properties/saray-lyxury/22.jpg",
      type: "FOR RENT",
    },
    {
      id: 3,
      title: "Golden Leaf Residence",
      price: "$780,000",
      address: "3456 Cedar Lane, Toronto, Canada",
      beds: 3,
      baths: 2,
      area: "900 sqft",
      image: "/images/properties/saray-lyxury/33.jpg",
      type: "FOR SALE",
    },

    {
        id: 4,
        title: "Golden Leaf Residence",
        price: "$780,000",
        address: "3456 Cedar Lane, Toronto, Canada",
        beds: 3,
        baths: 2,
        area: "900 sqft",
        image: "/images/properties/saray-lyxury/33.jpg",
        type: "FOR SALE",
      },

      {
        id: 5,
        title: "Golden Leaf Residence",
        price: "$780,000",
        address: "3456 Cedar Lane, Toronto, Canada",
        beds: 3,
        baths: 2,
        area: "900 sqft",
        image: "/images/properties/saray-lyxury/33.jpg",
        type: "FOR SALE",
      },
      
      {
        id: 6,
        title: "Golden Leaf Residence",
        price: "$780,000",
        address: "3456 Cedar Lane, Toronto, Canada",
        beds: 3,
        baths: 2,
        area: "900 sqft",
        image: "/images/properties/saray-lyxury/33.jpg",
        type: "FOR SALE",
      },
  ];